### ISSUE TITLE
Upgrade doesn't work without the reference

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1826]
## To Reproduce
1. Install a bundle
2. Run `porter upgrade` for the bundle and do not specify the --reference flag

## Expected behavior
It should use the reference stored on the installation document.

## Porter Command and Output
```console
$ porter upgrade porter-hello -n logger -r getporter/porter-hello:v0.1.1
upgrading porter-hello...

Using runtime driver docker
executing upgrade action from porter-hello (installation: porter-hello)
No existing bundle state to unpack
World 2.0
World 2.0
Packing bundle state...
execution completed successfully!
~/go/src/get.porter.sh/porter (structured-logging)$ porter upgrade porter-hello -n logger
panic: invalid reference format : invalid reference format

goroutine 1 [running]:
get.porter.sh/porter/pkg/porter.(*BundlePullOptions).GetReference(0xc0002c9f38, 0x2e4bbe1, 0x7)
	/Users/carolynvs/go/src/get.porter.sh/porter/pkg/porter/pull.go:24 +0x119
get.porter.sh/porter/pkg/porter.(*Porter).ExecuteAction(0xc0003111e0, 0x321a7d8, 0xc000056080, 0xc0008335b0, 0x5, 0xc0008335a0, 0xc, 0xc000833596, 0x6, 0x34536e78, ...)
	/Users/carolynvs/go/src/get.porter.sh/porter/pkg/porter/action.go:19 +0x385
get.porter.sh/porter/pkg/porter.(*Porter).UpgradeBundle(0xc0003111e0, 0xc0002c9e60, 0x0, 0x0, 0x0, 0x0)
	/Users/carolynvs/go/src/get.porter.sh/porter/pkg/porter/upgrade.go:92 +0x428
main.buildBundleUpgradeCommand.func2(0xc0003d8c80, 0xc000544300, 0x1, 0x3, 0x0, 0x0)
	/Users/carolynvs/go/src/get.porter.sh/porter/cmd/porter/bundle.go:199 +0x48
github.com/spf13/cobra.(*Command).execute(0xc0003d8c80, 0xc0005442d0, 0x3, 0x3, 0xc0003d8c80, 0xc0005442d0)
	/Users/carolynvs/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00025cf00, 0x31cc180, 0xc00013a5c0, 0x321a7d8)
	/Users/carolynvs/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/carolynvs/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/carolynvs/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
main.main.func1(0x0)
	/Users/carolynvs/go/src/get.porter.sh/porter/cmd/porter/main.go:38 +0x2e5
main.main()
	/Users/carolynvs/go/src/get.porter.sh/porter/cmd/porter/main.go:47 +0x2d
```

## Version
Copy the output of `porter version` below
v1.0.0-alpha.6-1-g26e5a477

**Comment by carolynvs** [comment]
Closing because this is only affecting my dev build, not the official build.
