### ISSUE TITLE
Enforce in bundle directory or --tag was specified

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#925]
I've noticed that we let commands get too far when run outside of a bundle directory, and no --tag is specified. So they then fail later because there isn't a bundle defined.

For example, I accidentally ran this invoke command a directory too high, and there isn't a porter.yaml in the directory. It should have immediately failed because of that. Instead if failed deeper when trying to execute the bundle.

```
$ porter invoke --action logs -c myapp

invoking custom action logs on ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x2293487]

goroutine 1 [running]:
get.porter.sh/porter/pkg/cnab/provider.(*Runtime).loadParameters(0xc000097a40, 0x0, 0xc00023ac60, 0x7ffeefbff60f, 0x4, 0x0, 0x0, 0xc0004b7400)
	/home/vsts/work/1/s/gopath/src/get.porter.sh/porter/pkg/cnab/provider/parameters.go:17 +0xc7
get.porter.sh/porter/pkg/cnab/provider.(*Runtime).Invoke(0xc000097a40, 0x7ffeefbff60f, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc00023ac90, 0x1, 0xc00023ac60, ...)
	/home/vsts/work/1/s/gopath/src/get.porter.sh/porter/pkg/cnab/provider/invoke.go:63 +0x114
get.porter.sh/porter/pkg/porter.(*Porter).InvokeBundle(0xc000350a00, 0x7ffeefbff60f, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/vsts/work/1/s/gopath/src/get.porter.sh/porter/pkg/porter/invoke.go:60 +0x4be
main.buildBundleInvokeCommand.func2(0xc00010ea00, 0xc0000b8d00, 0x0, 0x4, 0x0, 0x0)
	/home/vsts/work/1/s/gopath/src/get.porter.sh/porter/cmd/porter/bundle.go:187 +0x7e
github.com/spf13/cobra.(*Command).execute(0xc00010ea00, 0xc0000b8cc0, 0x4, 0x4, 0xc00010ea00, 0xc0000b8cc0)
	/home/vsts/work/1/s/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002bd180, 0x0, 0x24db640, 0xc000092058)
	/home/vsts/work/1/s/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/vsts/work/1/s/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/vsts/work/1/s/gopath/src/get.porter.sh/porter/cmd/porter/main.go:18 +0x27
make: *** [logs] Error 2
```

**Comment by carolynvs** [comment]
I can't reproduce this anymore after all the v1 refactoring. When I try to run a porter command when not in a bundle directory I get the following error:

```
no bundle specified. Either an installation name, --reference, --file or --cnab-file must be specified or the current directory must contain a porter.yaml file
```
